spring.application.name=Trucks-Logistics
# URL de conexión: jdbc:postgresql://[host]:[puerto]/[nombre_db]
spring.datasource.url=jdbc:postgresql://localhost:5432/Trucks Logistics

# Credenciales
spring.datasource.username=postgres
spring.datasource.password=habichuela77

# Driver oficial de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate / JPA
# update: crea o actualiza las tablas automáticamente según tus entidades
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola (útil para desarrollo)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto específico para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect