spring.application.name=Trucks-Logistics

spring.datasource.url=${DB_URL}

# Credenciales
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
jwt.secret=${JWT_SECRET:hwd55#$^&/.{OPwzxc4getfecrty*&^%$MNVEFVBOEfndrohdgljfjcnKLkxwbcvksjdns}
jwt.expiration-ms=900000

# Driver oficial de PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialecto específico para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Configuración básica de Mailtrap para Spring Boot
spring.mail.host=${MAILTRAP_HOST}
spring.mail.port=${MAILTRAP_PORT}
spring.mail.username=${MAILTRAP_USERNAME}
spring.mail.password=${MAILTRAP_PASSWORD}

# Propiedades adicionales obligatorias para SMTP
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

app.base-url=http://localhost:8080
app.verification-url=${app.base-url}/api/auth/verify?token=